name: studie
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.5
  percent_indicator: ^4.2.2
  flutter_riverpod: ^1.0.3+1
  permission_handler: ^10.0.2
  firebase_core: ^1.24.0
  cloud_firestore: ^3.5.0
  firebase_auth: ^3.11.0
  google_sign_in: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/svgs/
    - assets/fonts/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Regular.ttf
